# Index ile Elemanlara Erişmek

In [4]:
import numpy as np
a = np.random.randint(10,size = 10)
a

array([7, 1, 8, 8, 0, 5, 5, 7, 2, 3])

In [5]:
a[0]

7

In [9]:
a[-1]

3

In [7]:
a[0] = 100

In [8]:
a

array([100,   1,   8,   8,   0,   5,   5,   7,   2,   3])

In [11]:
m = np.random.randint(10,size = (3,5))
m

array([[5, 1, 4, 4, 7],
       [5, 8, 4, 6, 4],
       [2, 1, 6, 0, 8]])

In [12]:
m[0,0]

5

In [13]:
m[1,1]

8

In [14]:
m[1,4]

4

In [15]:
m[1,4] = 99

In [16]:
m

array([[ 5,  1,  4,  4,  7],
       [ 5,  8,  4,  6, 99],
       [ 2,  1,  6,  0,  8]])

In [17]:
m[1,4] = 2.2

In [18]:
m

array([[5, 1, 4, 4, 7],
       [5, 8, 4, 6, 2],
       [2, 1, 6, 0, 8]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[::2]

array([20, 22, 24, 26, 28])

In [8]:
a[2::2]

array([22, 24, 26, 28])

In [9]:
a[0::3]

array([20, 23, 26, 29])

# İki Boyutlu Slice İşlemleri

In [11]:
m = np.random.randint(10,size = (5,5))

In [12]:
m

array([[6, 6, 0, 2, 4],
       [7, 5, 9, 4, 6],
       [2, 4, 4, 4, 3],
       [1, 4, 6, 7, 9],
       [5, 4, 9, 0, 9]])

In [14]:
m[:,0]

array([6, 7, 2, 1, 5])

In [15]:
m[:,1]

array([6, 5, 4, 4, 4])

In [16]:
m[:,4]

array([4, 6, 3, 9, 9])

In [18]:
m

array([[6, 6, 0, 2, 4],
       [7, 5, 9, 4, 6],
       [2, 4, 4, 4, 3],
       [1, 4, 6, 7, 9],
       [5, 4, 9, 0, 9]])

In [17]:
m[0,:]

array([6, 6, 0, 2, 4])

In [19]:
m[1,:]

array([7, 5, 9, 4, 6])

In [20]:
m[0:2,0:3]

array([[6, 6, 0],
       [7, 5, 9]])

In [22]:
m[::,0:2]

array([[6, 6],
       [7, 5],
       [2, 4],
       [1, 4],
       [5, 4]])

In [23]:
m[1:3,0:2]

array([[7, 5],
       [2, 4]])

# Alt Küme Üzerinde İşlem Yapmak

In [24]:
import numpy as np
a = np.random.randint(10,size = (5,5))
a

array([[2, 7, 7, 9, 8],
       [9, 1, 0, 4, 4],
       [7, 8, 9, 7, 9],
       [8, 5, 4, 6, 2],
       [5, 6, 3, 8, 4]])

In [26]:
alt_a = a[0:3,0:2]
alt_a

array([[2, 7],
       [9, 1],
       [7, 8]])

In [28]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [29]:
alt_a

array([[99999,     7],
       [    9,   888],
       [    7,     8]])

In [30]:
a

array([[99999,     7,     7,     9,     8],
       [    9,   888,     0,     4,     4],
       [    7,     8,     9,     7,     9],
       [    8,     5,     4,     6,     2],
       [    5,     6,     3,     8,     4]])

In [31]:
m = np.random.randint(10,size = (5,5))
m

array([[8, 2, 7, 8, 2],
       [0, 7, 6, 7, 2],
       [4, 7, 3, 7, 1],
       [3, 8, 4, 6, 6],
       [7, 0, 1, 6, 0]])

In [33]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[8, 2],
       [0, 7],
       [4, 7]])

In [34]:
alt_b[0,0] = 9999

In [37]:
alt_b*3

array([[29997,     6],
       [    0,    21],
       [   12,    21]])

In [36]:
m

array([[8, 2, 7, 8, 2],
       [0, 7, 6, 7, 2],
       [4, 7, 3, 7, 1],
       [3, 8, 4, 6, 6],
       [7, 0, 1, 6, 0]])

# Fancy Index ile Elemanlara Erişmek

In [39]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [40]:
v[1]

3

In [41]:
v[3]

9

In [42]:
v[5]

15

In [43]:
v[1],v[3],v[5]

(3, 9, 15)

In [44]:
al_getir = [1,3,5]

In [45]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [46]:
v[al_getir]

array([ 3,  9, 15])

# İki Boyutta Fancy

In [47]:
m = np.arange(9).reshape((3,3))

In [48]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [50]:
m[satir,sutun]

array([1, 5])

# Basit Index ile Fancy Index

In [51]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
m[0,[1,2]]

array([1, 2])

# Slice ile Fancy

In [54]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [55]:
import numpy as np
v = np.array([1,2,3,4,5])

In [56]:
v > 5

array([False, False, False, False, False])

In [57]:
v < 3

array([ True,  True, False, False, False])

In [58]:
v[v < 3]

array([1, 2])

In [59]:
v[v > 3]

array([4, 5])

In [60]:
v[v >= 3]

array([3, 4, 5])

In [61]:
v[v <= 3]

array([1, 2, 3])

In [62]:
v[v == 3]

array([3])

In [63]:
v[v != 3]

array([1, 2, 4, 5])

In [64]:
v 

array([1, 2, 3, 4, 5])

In [65]:
v * 2

array([ 2,  4,  6,  8, 10])

In [66]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [68]:
v *5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [69]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)