# NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

# Sıfırdan Array Oluşturma

In [18]:
# sıfırlardan oluşan Array oluşturmak için kullanılır zeros fonksiyonu
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# birlerden oluşan Array oluşturmak için kullanılır ones fonksiyonu
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
# belirli bir sayıdan oluşan Array oluşturmak için kullanılır full fonksiyonu
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
# doğrusal bir dizi oluşturmak için kullanılır arange fonksiyonu
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [24]:
# İki değer arasında belirli sayıda değer oluşturmak için kullanılır linspace fonksiyonu
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
# Oluşturmak istediğim sayılar belirli bir dağılım yapısına uygun olsun Örneğin istatistik teorisinde yer alan normal dağılım gibi belirli bir standart sapma belirli bir ortalama vereyim ve bir array ya da iki boyutlu arrayin bilgisini tanımlamak için random.normal fonksiyonu kullanılır.
np.random.normal(10,4,(3,4))

array([[12.91586767, 10.28747712,  2.41074702, 14.30308562],
       [ 9.6357728 ,  8.83912244, 10.82122565,  6.34532522],
       [10.50268195, 15.3566758 ,  7.77491855, 11.06667824]])

In [27]:
# int değerlerden rastgele oluşturulmuş bir veri oluşturmak istersek random.radint fonksiyonunu kullanabiliriz.
np.random.randint(0,10,(3,3))

array([[4, 2, 3],
       [8, 4, 5],
       [5, 8, 8]])