# Yeniden Şekillendirme (reshaping)

In [2]:
import numpy as np

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = np.arange(1,10)

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.ndim

1

In [14]:
b = a.reshape((1,9))

In [15]:
b.ndim

2