In [1]:
import numpy as np

# Numpy Array

- Numpy arrayleri python listlerine benziyor.

- Ama onların aksine farklı veri tiplerinde eleman içeremez. Tek veri tipinde elemanları olması gerekiyor.

# Listlerden Array Oluşturmak

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array(["a","b","c"])

In [6]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
# Bütün integerlar string'e dönüştürülecek
z = np.array([1,2,3,"a"])

In [8]:
z

array(['1', '2', '3', 'a'], dtype='<U11')

In [9]:
a = np.array([1,2,3,"5"])

In [10]:
a

array(['1', '2', '3', '5'], dtype='<U11')

In [11]:
# Bütün integerlar float'a dönüştürülecek
b = np.array([1,2,3,4.5])

In [12]:
b

array([1. , 2. , 3. , 4.5])

In [13]:
# Bütün integerlar ve floatlar string e dönüştürülecek
c = np.array([1,2,3,4.5,"2"])

In [14]:
c

array(['1', '2', '3', '4.5', '2'], dtype='<U32')

# Array Data Tipini Manuel Belirtmek

In [16]:
x = np.array([1,2,3,4.6])

In [17]:
x

array([1. , 2. , 3. , 4.6])

In [18]:
x = np.array([1,2,3,4.6], dtype="int32")

In [19]:
x

array([1, 2, 3, 4])

In [20]:
x = np.array([1,2,3,4.5],dtype="str")

In [21]:
x

array(['1', '2', '3', '4.5'], dtype='<U3')

In [22]:
x = np.array(["a"],dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

In [23]:
x = np.array(["5"],dtype="int32")

In [24]:
x

array([5])

# Elemanları 0'lardan oluşan Array Oluşturmak

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

# Elemanları 0'lardan oluşan Multidimesional Array Oluşturmak

In [33]:
# 3 row(satır) ve 4 column(sütun)u olan bir array oluşturmak

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros([3,8,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [38]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [39]:
np.zeros(2, dtype=int)

array([0, 0])

In [40]:
np.zeros((1,2), dtype=int)

array([[0, 0]])

In [41]:
# "" lerden oluşan string array'i oluşturmak
np.zeros((1,2), dtype=str)

array([['', '']], dtype='<U1')

In [42]:
np.zeros((2,3),dtype = bool)

array([[False, False, False],
       [False, False, False]])

# Belirtilen Bir Elemandan Array Oluşturmak

In [43]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [44]:
np.full(4,5,5)

TypeError: Cannot interpret '5' as a data type

In [45]:
np.full(4,5)

array([5, 5, 5, 5])

In [46]:
np.full((4,5),"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [47]:
np.full((4,5),5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [49]:
str(5.2)

'5.2'

In [50]:
np.full((4,5),5.2,dtype=str)

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [51]:
np.full((4,5),"5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

# Ardışık Sayılardan Array Oluşturmak

In [58]:
#[0,12)
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [61]:
np.arange(2,12,-2)

array([], dtype=int32)

In [62]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

# Aralığı Eşit Uzaklıktaki Noktalara Bölmek

- Belirlenen [başlangıç,bitiş] değerine göre başlangıç ve bitişi dahil edecek şekilde, aralığı eşit uzaklıktaki noktalara bölmeyi göreceğiz

In [64]:
# Default olarak 50 nokta döndürür.
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

# Kaç Parçaya Bölüneceğini Belirtmek 

In [65]:
np.linspace(1,2,num = 3)

array([1. , 1.5, 2. ])

In [66]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [68]:
np.linspace(1,2,num = 3 ,endpoint = False)

array([1.        , 1.33333333, 1.66666667])

In [69]:
# 0 ve 1 arasında (0-1 dahil olacak şekilde) 30 nokta üretmek
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

- floatları da belirtilen sayıda bölebiliyoruz.

In [70]:
np.linspace(1.5,4.7,3)

array([1.5, 3.1, 4.7])

# Normal Distribution'dan Çekilmiş Değerler İle Array Oluşturmak

- (mean, std, array size)

In [73]:
np.random.normal(0,1, (4,5))

array([[-2.3327491 ,  0.60133067, -0.16655785,  2.06793123, -0.85680182],
       [-0.57228189, -1.5976544 , -0.83785354,  0.16589885,  1.17833793],
       [-0.63129136, -0.29909943, -0.36656216, -0.73468913,  0.08456652],
       [-0.91278358, -1.33542547,  1.08379392, -0.89831958,  1.13816962]])

In [74]:
np.random.normal(0,100, (4,5))

array([[ 180.85611978,  217.33761602,   23.88149232,   31.90539304,
        -165.30437894],
       [ -67.061439  ,   24.41495082,   58.87694939,   80.39178252,
          92.10679558],
       [-135.30006587,   19.813897  ,   51.52508801,  159.39816681,
         288.08053828],
       [  18.33515028,  -33.28937513,  162.88264224,  -55.00969383,
         144.74096896]])

In [75]:
np.random.normal(10,100, (4,5))

array([[  68.76317735,   38.5544651 ,   92.26259837,  -53.28932254,
         -94.10296182],
       [ -12.93176666,    9.32712973,  -19.52313566, -173.80480779,
         235.78663347],
       [ -39.57914299,   18.0048286 ,  -48.17939694,    8.46567889,
        -120.14487873],
       [  62.58074101,   98.15210456,   41.78627029,   48.24608483,
         148.2089944 ]])

In [76]:
np.random.normal(10,1, (4,5))

array([[11.36497301, 12.00410758, 10.29673349, 11.29847967, 11.47666456],
       [ 9.0023631 ,  9.38065579,  9.3808879 , 11.29447412,  9.38419494],
       [ 9.70383402, 10.07977732, 10.93011085, 11.06295589,  9.38347194],
       [ 7.75419757,  9.67183873, 11.45547962, 10.41808809, 10.67015383]])

# Random Integer'lar ile Array Oluşturmak
- [low,high)

In [77]:
np.random.randint(1,10,(3,4))

array([[6, 8, 8, 8],
       [2, 4, 1, 7],
       [2, 8, 6, 2]])

In [78]:
np.random.randint(1,10,(3,5,5))

array([[[8, 3, 9, 7, 5],
        [8, 6, 2, 8, 7],
        [1, 1, 8, 7, 9],
        [2, 9, 7, 2, 8],
        [9, 3, 8, 5, 5]],

       [[8, 5, 9, 2, 3],
        [9, 4, 1, 4, 3],
        [2, 6, 3, 9, 9],
        [1, 1, 7, 4, 8],
        [4, 8, 4, 9, 9]],

       [[8, 5, 9, 7, 7],
        [4, 2, 6, 3, 9],
        [6, 6, 9, 9, 2],
        [4, 8, 8, 8, 2],
        [2, 9, 1, 3, 1]]])

In [91]:
np.random.randint(1,3)

2

In [92]:
d = {}

for _ in range(20000):
    val = np.random.randint(1,11)
    
    if val not in d:
        d[val] = 1
    else:
        d[val] +=1

In [93]:
d

{5: 1921,
 7: 2043,
 8: 2021,
 2: 2030,
 3: 1934,
 1: 1975,
 10: 2093,
 9: 2071,
 6: 1936,
 4: 1976}

# Identity (birim) Matrix Oluşturmak
- [low,high)

In [94]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [95]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.eye(3,4)

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array İşlemleri

In [97]:
# * operatörü iki list arasında tanımsızdır hata verir.

a = [1,2,3]
b = [2,4,8]

a* b

TypeError: can't multiply sequence by non-int of type 'list'

- List ile integer çarpılırsa ard arda concatenation yapar

In [98]:
[2,4,8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [99]:
[2,4,8] + [2,4,8] + [2,4,8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

- `*` operatörü iki numpy arrayi arasında tanımlıdır. element-wise(eleman bazlı) çarpma yapar

In [119]:
x = np.array([1,2,3])
y = np.array([2,4,8])


x*y

array([ 2,  8, 24])

- element-wise çarpım yaptığı için çarpılan iki array'in eleman sayısı aynı olmalı

In [120]:
x2 = np.array([1,2,3])
y2 = np.array([2,4,8,10])


x2*y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [121]:
a = [1,2,3]
b = [2,4,8]

In [122]:
a+ b #concat yapar

[1, 2, 3, 2, 4, 8]

In [123]:
print(x)
print(y)

[1 2 3]
[2 4 8]


In [124]:
x+y

array([ 3,  6, 11])

In [125]:
a

[1, 2, 3]

In [126]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [127]:
x

array([1, 2, 3])

In [128]:
3*x

array([3, 6, 9])

In [129]:
x

array([1, 2, 3])

- değer güncellemek için

In [130]:
x = x * 3

In [132]:
x

array([3, 6, 9])

# Array Attribute'ları

# Shape

In [134]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [137]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [136]:
x.shape

(2, 3)

In [138]:
y.shape

(2, 5, 4)

# ndim

In [139]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [140]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [141]:
x.ndim

2

In [142]:
y.ndim

3

# Size 

In [143]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [144]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [145]:
x.size

6

In [146]:
y.size

40

# Dtype

In [147]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [148]:
x.dtype

dtype('float64')

# Reshaping
- Önemli nokta reshape yapacağımız yapının yaptıktan sonraki yapıyla aynı eleman sayısına sahip olması, yani size'ları aynı olacak

In [149]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
a.ndim

1

In [151]:
a.size

10

In [152]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [153]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [154]:
a.reshape(2,5).ndim

2

- Eleman sayısı tutmazsa hata alırım

In [155]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

# -1 ile Boyuta Karar Vermek

In [164]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Yeni Boyut Eklemek

In [157]:
a = np.arange(1,11)

In [159]:
a[np.newaxis,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [160]:
a[np.newaxis,:].shape

(1, 10)

In [165]:
# column vector

a[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [166]:
a[:,np.newaxis].shape

(10, 1)

In [167]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- Veya None olarak yazabiliriz

In [168]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [169]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# Concatenation

In [170]:
a = np.array([1,2,3,4])

In [171]:
b = np.array([5,6,7,8])

In [172]:
a

array([1, 2, 3, 4])

In [173]:
b

array([5, 6, 7, 8])

In [174]:
# a veya b güncellenemez
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

- python listlerini de numpy arrayleri ile concatenation'a sokabilirsiniz

In [175]:
l = [10,11]

In [177]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [178]:
l = [10,11,11.2]

In [179]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

- python tuple'larını da numpy arrayleri ile concatenation'a sokabiliriz

In [180]:
l = (10,11)

In [181]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

# Size Mismatch

In [182]:
a

array([1, 2, 3, 4])

In [184]:
x = np.array([[1,2,3],[4,5,6]])

In [185]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
x.size

6

In [187]:
x.shape

(2, 3)

In [188]:
a.shape

(4,)

In [189]:
#shape mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [190]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [192]:
np.concatenate([x,x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Stack

- Stack mantığını yeni dimension ekleyip o dimension üzerinde concatenation yaparak da sağlayabiliriz.

# stack

In [193]:
a = np.array([1,2,3,4])

In [194]:
b = np.array([5,6,7,8])

In [195]:
a.shape

(4,)

In [196]:
b.shape

(4,)

In [197]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [199]:
np.stack([a,b]).shape

(2, 4)

In [198]:
np.stack([a,b], axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [200]:
np.stack([a,b], axis = 1).shape

(4, 2)

# vstack

# Splitting

In [201]:
l = [10,20,30,40,50,60,70,80]

In [202]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [203]:
# [0,1], [2,3,4,5], [6,7]
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [204]:
np.split(l, [3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

# Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [205]:
a , b = (1,10)

In [207]:
print(a)
print(b)

1
10


In [208]:
x,y,z = np.split(l,[2,6])

In [209]:
print(x)
print(y)
print(z)


[10 20]
[30 40 50 60]
[70 80]


# vsplit

In [210]:
a = np.arange(20).reshape(2,10)

In [211]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [212]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [213]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [229]:
a = np.arange(20).reshape(5,4)

In [230]:
np.vsplit(a,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# hsplit

In [214]:
a = np.arange(20).reshape(2,10)

In [215]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [216]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [217]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [218]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [219]:
np.hsplit(a,[2])[0].shape

(2, 2)

In [220]:
np.hsplit(a,[2])[1].shape

(2, 8)

In [221]:
x, y = np.hsplit(a,[2])

In [223]:
print(x)

[[ 0  1]
 [10 11]]


In [224]:
print(y)

[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [225]:
x,y,z = np.hsplit(a,[2,4])

In [226]:
print(x)

[[ 0  1]
 [10 11]]


In [227]:
print(y)

[[ 2  3]
 [12 13]]


In [228]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


# Sorting

In [232]:
a = np.array([20,32,5,30,10])

In [234]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [235]:
a

array([20, 32,  5, 30, 10])

In [236]:
# a'yı günceller
a.sort() # inplace(a = np.sort(a) ile aynı)

In [237]:
a

array([ 5, 10, 20, 30, 32])

# argsort

In [238]:
a = np.array([3,1,6,5,4,2])

In [239]:
# kü.ükten büyüğe sıralanmış elemanların indexlerini döndürür
idsx = np.argsort(a)

In [240]:
idsx

array([1, 5, 0, 4, 3, 2], dtype=int64)

# Multidimensional Arraylerin Elemanlarına Ulaşmak

In [241]:
a = np.arange(1,21).reshape(4,5)

In [242]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [243]:
a[0]

array([1, 2, 3, 4, 5])

In [244]:
a[1]

array([ 6,  7,  8,  9, 10])

In [245]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [246]:
a[0,0]

1

In [247]:
a[0][0]

1

In [248]:
a[1,1]

7

In [249]:
a[0,1]

2

In [250]:
a.ndim

2

In [251]:
a[0]

array([1, 2, 3, 4, 5])

In [253]:
a[0].ndim

1

In [254]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [255]:
a[1,1] = 10

In [256]:
a
 

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [257]:
# Array'in veri tipi neyse ona cast olur, array in veri tipini dönüştürmez !
a[1,1] = 20.40

In [258]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [259]:
a[1,1] = "30"

In [260]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [262]:
a[1,1] = "30.5"

ValueError: invalid literal for int() with base 10: '30.5'

In [263]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Slice Indexing

In [264]:
a = np.arange(1,21).reshape(4,5)

In [265]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [266]:
a[1]

array([ 6,  7,  8,  9, 10])

In [267]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [268]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [269]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [270]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [271]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [272]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [273]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [274]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [275]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [276]:
a[2,3]

14

In [277]:
# bütün rowları al ama sadece 3.indexteki column u al
a[:,3]

array([ 4,  9, 14, 19])

In [279]:
a[::2,3]

array([ 4, 14])

In [280]:
a[0,:]

array([1, 2, 3, 4, 5])

In [281]:
a[0]

array([1, 2, 3, 4, 5])

In [282]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [283]:
a[0,2:4]

array([3, 4])

In [284]:
a[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [285]:
a[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [286]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [287]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [288]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

# Fancy Indexing

- Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları veya belirli sayıda atlaya atlaya elemanları almayı gördük. Facy indexing ile bir kaç tane belirli indexteki elemanı bana döndür demiş olacağız

In [294]:
x = np.arange(1,15)

In [295]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [296]:
idsx = [4,5,7,11]

In [297]:
# 4,5,7 ve 11. indexteki elemanları döndürür.
x[idsx]

array([ 5,  6,  8, 12])

In [304]:
idsx = [4,5,7,1]

In [306]:
x[idsx]

array([5, 6, 8, 2])

In [307]:
a = np.arange(12).reshape(3,4)

In [308]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [309]:
a[0:2,1]

array([1, 5])

In [310]:
a[0:2,1].shape

(2,)

In [311]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [312]:
a[0:2,1:3].shape

(2, 2)

In [313]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [314]:
a[0,[1,3]]

array([1, 3])

In [315]:
a[0:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [316]:
a = np.arange(20).reshape(4,5)

In [317]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [324]:
idx1 = [1,3,2]

In [325]:
idx2 = [3,0,2]

In [326]:
a[idx1,idx2]

array([ 8, 15, 12])

In [327]:
a[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

- Fancy indexing sonucunu belirli değerlere eşitlemek

In [328]:
x[[1,2,3]] = 20

In [330]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [331]:
x = np.arange(9)

In [332]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [337]:
x[[1,2,5]] = [100,200,300]

In [338]:
x

array([  0, 100, 200, 300,   4, 300,   6,   7,   8])

In [335]:
t = (1,2,3,4,5,6)

In [336]:
t

(1, 2, 3, 4, 5, 6)

In [339]:
t[3]

4

# Subarray

In [340]:
a = np.arange(1,21).reshape(4,5)

In [341]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [342]:
b = a[:2,:3]

In [343]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [344]:
b.ndim

2

In [346]:
b[0,0] = 100

In [347]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [348]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

# Copy

In [356]:
a = np.arange(1,21).reshape(4,5)

In [357]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [358]:
b = a[:2,:3].copy()

In [359]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [360]:
b[0,0] = 100

In [361]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [362]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Conditional Indexing

In [364]:
a = np.arange(1,10)

In [365]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [366]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [367]:
a[a<5]

array([1, 2, 3, 4])

In [368]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [369]:
filt = a< 3

In [370]:
a[filt]

array([1, 2])

In [371]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [372]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [373]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [374]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [375]:
a[a==b]

array([3, 4, 5, 7, 8])

In [376]:
b[a==b]

array([3, 4, 5, 7, 8])

In [377]:
#broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [378]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [379]:
# normalde and or ile kurduğumuz mantığı numpy'da kullanamıyoruz.
(a<3) or (a>5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [380]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [381]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [382]:
filt = (a<3) | (a>5)

In [383]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [384]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [385]:
a[(a<3) & (a<=5)]

array([1, 2])

# Filtrenin Değili

In [386]:
a = np.arange(1,21).reshape(4,5)

In [387]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [390]:
filt = a < 5

In [391]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [392]:
a[filt]

array([1, 2, 3, 4])

In [393]:
filt = (a>5) & (a<9)

In [394]:
a[!((a>5) & (a<9))]

SyntaxError: invalid syntax (1998864425.py, line 1)

In [395]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [396]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [397]:
filt = ~((a>5) & (a<9))

In [398]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Multidimensional Array'lerde Conditional Indexing

In [399]:
a = np.arange(1,21).reshape(4,5)

In [400]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [402]:
type(a)

numpy.ndarray

In [403]:
type(a<7)

numpy.ndarray

In [404]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [405]:
a[a<7].shape

(6,)

In [406]:
a = np.array([1,2,3,None])

In [407]:
a

array([1, 2, 3, None], dtype=object)

In [408]:
a == None

array([False, False, False,  True])

In [409]:
a[a==None]

array([None], dtype=object)

# sum
- Verilen Condition'ı kaç elemanın sağladığını bulalım

In [410]:
a = np.arange(1,21).reshape(4,5)

In [411]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [412]:
np.sum(a)

210

In [413]:
filt = a < 5

In [414]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [415]:
np.sum(filt)

4

In [416]:
a[filt]

array([1, 2, 3, 4])

In [417]:
np.sum(a[filt])

10

In [418]:
filt = (a>5) & (a<9)

In [419]:
np.sum(filt)

3

In [420]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [421]:
a[filt]

array([6, 7, 8])

In [422]:
np.sum(a[(a>5) & (a<9)])

21

In [423]:
filt = ~((a>5) & (a<9))

In [424]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [425]:
np.sum(~((a>5) & (a<9)))

17

In [426]:
np.sum(a[~((a>5) & (a<9))])

189

# Belirli axis Üzerinde Toplama

In [427]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [431]:
np.sum(a,axis = 0)

array([34, 38, 42, 46, 50])

In [429]:
np.sum(a,axis = 1)

array([15, 40, 65, 90])

# All
- Tüm Elemanlar verilen şartı sağlıyor mu kontrol etmek

In [432]:
a = np.arange(20).reshape(4,5)

In [433]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [434]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [435]:
np.all(a>-1)

True

In [436]:
filt = a>-1

In [437]:
np.all(filt)

True

In [438]:
np.all(a>-1,axis = 1)

array([ True,  True,  True,  True])

In [439]:
np.all(a>-1,axis= 0)

array([ True,  True,  True,  True,  True])

In [440]:
a>4

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [441]:
np.all(a>4)

False

# any

In [442]:
a = np.arange(20).reshape(4,5)

In [443]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [444]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [445]:
np.any(a>17)

True

In [446]:
np.any(a>17,axis=0)

array([False, False, False,  True,  True])

In [447]:
np.any(a>17,axis=1)

array([False, False, False,  True])