In [3]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array([benimListem])

array([[20, 30, 40]])

In [5]:
type(np.array([benimListem]))

numpy.ndarray

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
type(matrixListesi)

list

In [8]:
matrixListesi[1][0]

20

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## ones

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [25]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## eye

In [27]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [29]:
np.random.randn(4)

array([-0.53840285, -0.38344666, -1.56606231,  0.75233061])

In [31]:
np.random.randn(4,4)

array([[ 0.7483032 , -0.34524552, -1.83346874,  0.75875323],
       [ 0.51282347,  1.35144771, -0.18332525, -2.28238821],
       [-1.23359681,  0.18130385,  0.63254542, -0.28580726],
       [ 0.31927713, -0.79744984, -1.92784456,  0.87413362]])

In [35]:
np.random.randint(1,10)

7

In [40]:
np.random.randint(1,300,5)

array([211,   1, 188, 245, 289])

In [41]:
benimNumpyDizim = np.arange(30)

In [42]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
benimRandomDizim = np.random.randint(0,100,20)

In [46]:
benimRandomDizim

array([88, 97, 25, 99, 79, 34, 24, 79, 67, 43, 67, 29, 54, 36,  4, 27, 51,
       44, 51,  2])

## numpy dizi metotları

In [51]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [52]:
benimNumpyDizim.max()

29

In [54]:
benimRandomDizim.max()

99

In [53]:
benimNumpyDizim.min()

0

In [55]:
benimRandomDizim.min()

2

In [56]:
benimRandomDizim.argmax()

3

In [57]:
benimRandomDizim.argmin()

19

In [66]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [68]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
reshapeDizim.shape

(5, 6)

# Numpy Operasyonlar

In [70]:
benimDizim = np.arange(0,15)

In [71]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
benimDizim[5]

5

In [74]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [75]:
benimDizim[3:8] = -5

In [76]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [77]:
baskaDizi = np.arange(0,24)

In [78]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [89]:
slicingDizisi = baskaDizi[4:9]

In [90]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [91]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [92]:
slicingDizisi[:] = 700

In [93]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [94]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [95]:
ornekDizi = np.arange(0,24)

In [96]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [97]:
ornekDiziKopyasi = ornekDizi.copy()

In [98]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [99]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [102]:
ornekDiziKopyaSlicing[:] = 800

In [103]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [104]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [105]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix


In [1]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [6]:
benimMatrixDizim = np.array(benimListem)

In [7]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [8]:
benimMatrixDizim[0]

array([10, 20, 30])

In [9]:
benimMatrixDizim[1][2]

40

In [10]:
benimMatrixDizim[1,2]

40

In [11]:
benimMatrixDizim[:]

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [15]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [21]:
benimMatrixDizim[2:,2:]

array([[60]])

In [24]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [25]:
yeniMatrix = np.array(yeniListe)

In [26]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [29]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# Operasyonlar

In [32]:
yeniBirDizi = np.random.randint(1,100,20)

In [33]:
yeniBirDizi

array([81, 42, 64, 79, 72, 30,  9, 63, 44, 83, 99,  8, 90, 12, 98, 98, 65,
       40, 79, 28])

In [34]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True])

In [35]:
yeniBirDizi

array([81, 42, 64, 79, 72, 30,  9, 63, 44, 83, 99,  8, 90, 12, 98, 98, 65,
       40, 79, 28])

In [36]:
sonucDizisi = yeniBirDizi > 24

In [37]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True])

In [38]:
yeniBirDizi

array([81, 42, 64, 79, 72, 30,  9, 63, 44, 83, 99,  8, 90, 12, 98, 98, 65,
       40, 79, 28])

In [39]:
yeniBirDizi[sonucDizisi]

array([81, 42, 64, 79, 72, 30, 63, 44, 83, 99, 90, 98, 98, 65, 40, 79, 28])

In [41]:
yeniBirDizi

array([81, 42, 64, 79, 72, 30,  9, 63, 44, 83, 99,  8, 90, 12, 98, 98, 65,
       40, 79, 28])

In [40]:
yeniBirDizi[yeniBirDizi > 24]

array([81, 42, 64, 79, 72, 30, 63, 44, 83, 99, 90, 98, 98, 65, 40, 79, 28])

In [42]:
sonDizi = np.arange(0,24)

In [43]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [44]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [46]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [47]:
sonDizi / sonDizi

C:\Users\musau\AppData\Local\Temp\ipykernel_17244\1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [48]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [49]:
np.max(sonDizi)

23

In [50]:
np.min(sonDizi)

0